<a href="https://colab.research.google.com/github/pirgus/MLclassifiers/blob/main/Classificadores_A_M_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Classificadores Monolíticos e Sistemas de Múltiplos Classificadores - Trabalho de Aprendizagem de Máquina
Davi M. Giacomel e Jaqueline C. Faino

In [ ]:
import pandas as pd
import sklearn as sk
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
dados = pd.read_csv("ILPD_nonorm.csv", header=None)

# substituição das strings de gênero por valores numéricos
gender = {'Male': 1,'Female': 2}
dados[1] = [gender[item] for item in dados[1]]

#dados.head()

In [ ]:
df_dados = pd.DataFrame(dados)
df_dados = df_dados.drop(10, axis=1)
df_dados = df_dados.interpolate(method='linear') # substituindo os valores NAN com base nos valores vizinhos
#df_dados.info()
#figura = df_dados.plot.scatter(x=0,y=5,c=10,colormap='rainbow')

In [ ]:
from sklearn.model_selection import train_test_split
x_treino,x_temp,y_treino,y_temp=train_test_split(df_dados,dados[10],test_size=0.5,stratify=dados[10])
x_validacao,x_teste,y_validacao,y_teste=train_test_split(x_temp,y_temp,test_size=0.5, stratify = y_temp)
#print("Treino")
#x_treino.info()
#y_treino.info()
#print("\nValidação")
#x_validacao.info()
#y_validacao.info()
#print("\nTeste")
#x_teste.info()
#y_teste.info()

NameError: ignored

Plotando a Curva ROC

In [ ]:
import matplotlib.pyplot as plt

from sklearn import metrics
def plot_roc_curve(fper, tper,cor,classsificador):
    plt.plot(fper, tper, color=cor, label=classsificador)
    plt.plot([0, 1], [0, 1], color="green", linestyle='--')
    plt.xlabel('Taxa de Falsos Positivos (FPR)')
    plt.ylabel('Taxa de Verdadeiros Positivos (TPR)')
    plt.title('Curva ROC')
    plt.legend()

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.model_selection import ParameterGrid
from sklearn.neighbors import KNeighborsClassifier

#geracao da lista para grid search
grid_parameters = ParameterGrid({'k': list(range(1,11)), 'w' : ['distance', 'uniform']})
#print(list(grid_parameters))

maior_acuracia = -1000
for i in grid_parameters:
  KNN = KNeighborsClassifier(n_neighbors = i['k'], weights = i['w'])
  KNN.fit(x_treino,y_treino)
  opiniao = KNN.predict(x_teste)
  acuracia = accuracy_score(y_validacao, opiniao)
  #print("K: ", i['k']," Métrica: ",i['w']," Acc: ",acuracia)
  if (acuracia > maior_acuracia):
      maior_acuracia = acuracia
      melhor_k = i['k']
      melhor_metrica = i['w']

#print("\nMelhor configuração para o KNN: ")
print("K: ",melhor_k," Métrica: ",melhor_metrica," Acc: ",maior_acuracia)

K:  10  Métrica:  uniform  Acc:  0.6712328767123288


In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.model_selection import ParameterGrid
from sklearn import svm

#geracao da lista para grid search
grid_parameters = ParameterGrid({'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'c' : [0.001, 0.1, 1.0, 10.0, 100.0]})
#print(list(grid_parameters))

maior_acuracia = -1000
for i in grid_parameters:
  SVM = svm.SVC(probability = True, kernel = i['kernel'], C = i['c'])
  SVM.fit(x_treino, y_treino)
  opiniao = SVM.predict(x_teste)
  acuracia = accuracy_score(y_validacao, opiniao)
  #print("K: ", i['kernel']," Métrica: ",i['c']," Acc: ",acuracia)
  if (acuracia > maior_acuracia):
      maior_acuracia = acuracia
      melhor_kernel = i['kernel']
      melhor_c = i['c']

print("\nMelhor configuração para o SVM: ")
print("Kernel: ", melhor_kernel," Métrica: ",melhor_c," Acc: ",maior_acuracia)


Melhor configuração para o SVM: 
Kernel:  linear  Métrica:  0.001  Acc:  0.7123287671232876


In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.model_selection import ParameterGrid
from sklearn.neural_network import MLPClassifier
from sklearn import svm

#geracao da lista para grid search
grid_parameters = ParameterGrid({'hls': list(range(50,100+1, 10)),
                                 'activation' : ['identity', 'logistic', 'tanh', 'relu'],
                                 'max_iter' : list(range(250,300+1, 10)),
                                 'l_rate': ['constant', 'invscaling', 'adaptive']})

maior_acuracia = -1000
count = 0
for i in grid_parameters:
  #print("---------------------------------- iteracao n", count, "----------------------------------")
  count = count + 1
  MLP = MLPClassifier(max_iter = i['max_iter'], activation= i['activation'],
                      hidden_layer_sizes= i['hls'], learning_rate = i['l_rate']
                      ).fit(x_treino, y_treino)

  opiniao = MLP.predict(x_teste)
  acuracia = accuracy_score(y_validacao, opiniao)
  #print("Max_iter: ", i['max_iter']," Activation: ",i['activation'], "l_rate: ", i['l_rate'],
       # "Hidden layer size: ", i['hls'], " Acc: ",acuracia)
  if (acuracia > maior_acuracia):
      maior_acuracia = acuracia
      melhores_parametros_MLP = i

print("\nMelhor configuração para o MLP: ")
print("Max_iter: ", melhores_parametros_MLP['max_iter']," Activation: ",
      melhores_parametros_MLP['activation'], "l_rate: ", melhores_parametros_MLP['l_rate'],
      "Hidden layer size: ", melhores_parametros_MLP['hls'], " Acc: ", maior_acuracia)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (250) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (260) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (270) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (280) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptro


Melhor configuração para o MLP: 
Max_iter:  250  Activation:  identity l_rate:  adaptive Hidden layer size:  60  Acc:  0.7191780821917808


In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.model_selection import ParameterGrid
from sklearn import tree


#geracao da lista para grid search
grid_parameters = ParameterGrid({'criterion': ['gini', 'entropy', 'log_loss'], 'max_depth': list(range(10, 100, 5))+[None],
                                 'min_samples_split': list(range(10, 100, 5)), 'min_samples_leaf': [1, 2, 3, 4, 5]})

maior_acuracia = -1000
for i in grid_parameters:
  DT = tree.DecisionTreeClassifier(criterion=i['criterion'], max_depth=i['max_depth'], min_samples_split=i['min_samples_split'],
                                   min_samples_leaf=i['min_samples_leaf']).fit(x_treino, y_treino)

  opiniao = DT.predict(x_teste)
  acuracia = accuracy_score(y_validacao, opiniao)
  #print("criterion=", i['criterion'], " max_depth=", i['max_depth'], " min_samples_split=", i['min_samples_split'],
  #                                 " min_samples_leaf=", i['min_samples_leaf'], " Acc: ",acuracia)
  if (acuracia > maior_acuracia):
      maior_acuracia = acuracia
      melhores_parametros_DT = i

print("\nMelhor configuração para DT: ")
print("criterion=", melhores_parametros_DT['criterion'], " max_depth=", melhores_parametros_DT['max_depth'],
      " min_samples_split=", melhores_parametros_DT['min_samples_split'], " min_samples_leaf=", melhores_parametros_DT['min_samples_leaf'],
      " Acc: ", maior_acuracia)


Melhor configuração para DT: 
criterion= gini  max_depth= 10  min_samples_split= 10  min_samples_leaf= 4  Acc:  0.6575342465753424


In [ ]:
from IPython.utils.text import string
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB


for i in range(20):
  print("---------------------------- iteracao n", i, "----------------------------")
  x_treino,x_temp,y_treino,y_temp=train_test_split(df_dados,dados[10],test_size=0.5,stratify=dados[10])
  x_validacao,x_teste,y_validacao,y_teste=train_test_split(x_temp,y_temp,test_size=0.5, stratify = y_temp)

  KNN = KNeighborsClassifier(n_neighbors=melhor_k, weights=melhor_metrica)
  KNN.fit(x_treino,y_treino)
  opiniao = KNN.predict(x_teste)
  #print("\nDesempenho do KNN")
  #print("Qtd de vizinhos: ", KNN.n_neighbors)
  #print(classification_report(y_teste,opiniao))
  y_score = KNN.predict_proba(x_teste)[:,1]
  fpr, tpr, thresholds = metrics.roc_curve(y_teste,y_score,pos_label=2)
  print(metrics.auc(fpr,tpr))
  #plot_roc_curve(fpr, tpr,"red","KNN")


  SVM = svm.SVC(probability=True, C=melhor_c, kernel=melhor_kernel)
  SVM.fit(x_treino, y_treino)
  opiniao = SVM.predict(x_teste)
  #print("\nDesempenho do SVM")
  #print(classification_report(y_teste, opiniao, zero_division=0))
  y_score = SVM.predict_proba(x_teste)[:,1]
  fpr, tpr, thresholds = metrics.roc_curve(y_teste,y_score,pos_label=2)
  print(metrics.auc(fpr,tpr))
  #plot_roc_curve(fpr, tpr,"purple","SVM")
  #print(y_teste)


  MLP = MLPClassifier(random_state=1, max_iter=melhores_parametros_MLP['max_iter'], activation=melhores_parametros_MLP['activation'],
                      hidden_layer_sizes=melhores_parametros_MLP['hls'], learning_rate=melhores_parametros_MLP['l_rate']
                      ).fit(x_treino, y_treino)

  opiniao = MLP.predict(x_teste)
  #print("\nDesempenho do MLP")
  #print(classification_report(y_teste, opiniao))
  y_score = MLP.predict_proba(x_teste)[:,1]
  fpr, tpr, thresholds = metrics.roc_curve(y_teste,y_score,pos_label=2)
  print(metrics.auc(fpr,tpr))
  #plot_roc_curve(fpr, tpr,"pink","MLP")


  NB = GaussianNB()
  NB.fit(x_treino,y_treino)
  opiniao = NB.predict(x_teste)
  #print("\nDesempenho do Naive Bayes")
  #print(classification_report(y_teste,opiniao))
  y_score = NB.predict_proba(x_teste)[:,1]
  fpr, tpr, thresholds = metrics.roc_curve(y_teste,y_score,pos_label=2)
  print(metrics.auc(fpr,tpr))
  #plot_roc_curve(fpr, tpr,"blue","NaiVe Bayes")


  DT = tree.DecisionTreeClassifier(criterion=melhores_parametros_DT['criterion'], max_depth=melhores_parametros_DT['max_depth'],
                                  min_samples_split=melhores_parametros_DT['min_samples_split'], min_samples_leaf=melhores_parametros_DT['min_samples_leaf'])
  DT.fit(x_treino,y_treino)
  opiniao = DT.predict(x_teste)
  #print("\nDesempenho da Árvore de Decisão")
  #print(classification_report(y_teste,opiniao))
  y_score = DT.predict_proba(x_teste)[:,1]
  fpr, tpr, thresholds = metrics.roc_curve(y_teste,y_score,pos_label=2)
  print(metrics.auc(fpr,tpr))
  #plot_roc_curve(fpr, tpr,"black","DT")


---------------------------- iteracao n 0 ----------------------------
0.6393086080586081
0.7209249084249084
0.7298534798534798
0.7106227106227107
0.575091575091575
---------------------------- iteracao n 1 ----------------------------
0.6391941391941393
0.6858974358974359
0.7392399267399267
0.7074175824175825
0.5596382783882784
---------------------------- iteracao n 2 ----------------------------
0.7351190476190476
0.7456501831501832
0.8019688644688645
0.7442765567765567
0.7461080586080586
---------------------------- iteracao n 3 ----------------------------
0.6766254578754579
0.6939102564102564
0.739010989010989
0.7184065934065934
0.6417124542124543
---------------------------- iteracao n 4 ----------------------------
0.7409569597069596
0.7016941391941391
0.7751831501831502
0.7133699633699634
0.6403388278388279
---------------------------- iteracao n 5 ----------------------------
0.7560668498168498
0.5538003663003663
0.8205128205128205
0.764423076923077
0.6364468864468864
-------

In [ ]:
from IPython.utils.text import string
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn import svm
from sklearn import tree

x_treino,x_temp,y_treino,y_temp=train_test_split(df_dados,dados[10],test_size=0.5,stratify=dados[10])
x_validacao,x_teste,y_validacao,y_teste=train_test_split(x_temp,y_temp,test_size=0.5, stratify = y_temp)

KNN = KNeighborsClassifier()
KNN.fit(x_treino,y_treino)
opiniao = KNN.predict(x_teste)
print("\nDesempenho do KNN")
print("Qtd de vizinhos: ", KNN.n_neighbors)
print(classification_report(y_teste,opiniao))
y_score = KNN.predict_proba(x_teste)[:,1]
fpr, tpr, thresholds = metrics.roc_curve(y_teste,y_score,pos_label=2)
print(metrics.auc(fpr,tpr))
plot_roc_curve(fpr, tpr,"red","KNN")

SVM = svm.SVC(probability=True)
SVM.fit(x_treino, y_treino)
opiniao = SVM.predict(x_teste)
print("\nDesempenho do SVM")
print(classification_report(y_teste, opiniao, zero_division=0))
y_score = SVM.predict_proba(x_teste)[:,1]
fpr, tpr, thresholds = metrics.roc_curve(y_teste,y_score,pos_label=2)
print(metrics.auc(fpr,tpr))
plot_roc_curve(fpr, tpr,"purple","SVM")
print(y_teste)


MLP = MLPClassifier().fit(x_treino, y_treino)

opiniao = MLP.predict(x_teste)
print("\nDesempenho do MLP")
print(classification_report(y_teste, opiniao))
y_score = MLP.predict_proba(x_teste)[:,1]
fpr, tpr, thresholds = metrics.roc_curve(y_teste,y_score,pos_label=2)
print(metrics.auc(fpr,tpr))
plot_roc_curve(fpr, tpr,"pink","MLP")


NB = GaussianNB()
NB.fit(x_treino,y_treino)
opiniao = NB.predict(x_teste)
print("\nDesempenho do Naive Bayes")
print(classification_report(y_teste,opiniao))
y_score = NB.predict_proba(x_teste)[:,1]
fpr, tpr, thresholds = metrics.roc_curve(y_teste,y_score,pos_label=2)
print(metrics.auc(fpr,tpr))
plot_roc_curve(fpr, tpr,"blue","NaiVe Bayes")


DT = tree.DecisionTreeClassifier()
DT.fit(x_treino,y_treino)
opiniao = DT.predict(x_teste)
print("\nDesempenho da Árvore de Decisão")
print(classification_report(y_teste,opiniao))
y_score = DT.predict_proba(x_teste)[:,1]
fpr, tpr, thresholds = metrics.roc_curve(y_teste,y_score,pos_label=2)
print(metrics.auc(fpr,tpr))
plot_roc_curve(fpr, tpr,"black","DT")

## Combinação por Regra da Soma

In [ ]:
from sklearn.metrics._plot.confusion_matrix import confusion_matrix
from IPython.utils.text import string
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

#regra da soma

for i in range(20):
  #print("-------------- iteracao n ", i, "----------------")
  x_treino,x_temp,y_treino,y_temp=train_test_split(df_dados,dados[10],test_size=0.5,stratify=dados[10], random_state = i)
  x_validacao,x_teste,y_validacao,y_teste=train_test_split(x_temp,y_temp,test_size=0.5, stratify = y_temp, random_state = i)

  # initialize a group of classifiers
  DT = tree.DecisionTreeClassifier(criterion=melhores_parametros_DT['criterion'], max_depth=melhores_parametros_DT['max_depth'],
                                  min_samples_split=melhores_parametros_DT['min_samples_split'], min_samples_leaf=melhores_parametros_DT['min_samples_leaf'])
  DT.fit(x_treino, y_treino)

  KNN = KNeighborsClassifier(n_neighbors=melhor_k, weights=melhor_metrica)
  KNN.fit(x_treino, y_treino)
  #print(KNN.predict_proba(x_teste))

  SVM = svm.SVC(probability=True, C=melhor_c, kernel=melhor_kernel)
  SVM.fit(x_treino, y_treino)

  MLP = MLPClassifier(max_iter=melhores_parametros_MLP['max_iter'], activation=melhores_parametros_MLP['activation'],
                      hidden_layer_sizes=melhores_parametros_MLP['hls'], learning_rate=melhores_parametros_MLP['l_rate'])

  MLP.fit(x_treino, y_treino)

  NB = GaussianNB()
  NB.fit(x_treino, y_treino)

  classifiers = [DT, KNN, SVM, MLP, NB]

  predictions_ = list()
  for classifier in classifiers:
    predictions_.append(classifier.predict_proba(x_teste))
    #print(predictions_)
  #print("soma")
  soma_prob = np.sum(predictions_, axis=0)
  #print(soma_prob)
  #print(np.sum(predictions_, axis=0))
  resultado = []


  for i in soma_prob:
    if (i[0] > i[1]):
      resultado.append(1)
    else:
      resultado.append(2)

  #print(resultado)
  #print(y_teste)
  matrix = confusion_matrix(y_teste, resultado)
  print("Matriz de confusão:")
  print(matrix)
  accuracy = (matrix[0][0] + matrix[1][1]) / (146)
  print("acuracia = ", accuracy)


Matriz de confusão:
[[79 25]
 [17 25]]
acuracia =  0.7123287671232876
Matriz de confusão:
[[80 24]
 [19 23]]
acuracia =  0.7054794520547946
Matriz de confusão:
[[95  9]
 [27 15]]
acuracia =  0.7534246575342466
Matriz de confusão:
[[72 32]
 [16 26]]
acuracia =  0.6712328767123288
Matriz de confusão:
[[78 26]
 [15 27]]
acuracia =  0.7191780821917808
Matriz de confusão:
[[77 27]
 [22 20]]
acuracia =  0.6643835616438356
Matriz de confusão:
[[78 26]
 [25 17]]
acuracia =  0.6506849315068494
Matriz de confusão:
[[91 13]
 [30 12]]
acuracia =  0.7054794520547946
Matriz de confusão:
[[76 28]
 [21 21]]
acuracia =  0.6643835616438356
Matriz de confusão:
[[81 23]
 [19 23]]
acuracia =  0.7123287671232876
Matriz de confusão:
[[81 23]
 [25 17]]
acuracia =  0.6712328767123288
Matriz de confusão:
[[80 24]
 [21 21]]
acuracia =  0.6917808219178082
Matriz de confusão:
[[100   4]
 [ 37   5]]
acuracia =  0.7191780821917808
Matriz de confusão:
[[71 33]
 [22 20]]
acuracia =  0.6232876712328768
Matriz de confus

## Combinação por voto majoritário

In [ ]:
from sklearn.ensemble import VotingClassifier


# voto majoritário

for i in range(20):
  #print("-------------- iteracao n ", i, "----------------")
  x_treino,x_temp,y_treino,y_temp=train_test_split(df_dados,dados[10],test_size=0.5,stratify=dados[10], random_state = i)
  x_validacao,x_teste,y_validacao,y_teste=train_test_split(x_temp,y_temp,test_size=0.5, stratify = y_temp, random_state = i)

  # initialize a group of classifiers
  DT = tree.DecisionTreeClassifier(criterion=melhores_parametros_DT['criterion'], max_depth=melhores_parametros_DT['max_depth'],
                                  min_samples_split=melhores_parametros_DT['min_samples_split'], min_samples_leaf=melhores_parametros_DT['min_samples_leaf'])
  #DT.fit(x_treino, y_treino)

  KNN = KNeighborsClassifier(n_neighbors=melhor_k, weights=melhor_metrica)
  #KNN.fit(x_treino, y_treino)
  #print(KNN.predict(x_teste))

  SVM = svm.SVC(probability=True, C=melhor_c, kernel=melhor_kernel)
  #SVM.fit(x_treino, y_treino)

  MLP = MLPClassifier(max_iter=melhores_parametros_MLP['max_iter'], activation=melhores_parametros_MLP['activation'],
                      hidden_layer_sizes=melhores_parametros_MLP['hls'], learning_rate=melhores_parametros_MLP['l_rate'])

  #MLP.fit(x_treino, y_treino)

  NB = GaussianNB()
  #NB.fit(x_treino, y_treino)

  classifiers = [('dt', DT), ('knn', KNN), ('svm', SVM), ('mlp', MLP), ('nb', NB)]

  voting = VotingClassifier(classifiers, voting='hard')
  voting.fit(x_treino, y_treino)
  resultado = voting.predict(x_teste)

  matrix = confusion_matrix(y_teste, resultado)
  print("Matriz de confusão")
  print(matrix)
  accuracy = (matrix[0][0] + matrix[1][1]) / (146)
  print("acuracia = ", accuracy)

Matriz de confusão
[[101   3]
 [ 39   3]]
acuracia =  0.7123287671232876
Matriz de confusão
[[91 13]
 [31 11]]
acuracia =  0.6986301369863014
Matriz de confusão
[[102   2]
 [ 37   5]]
acuracia =  0.7328767123287672
Matriz de confusão
[[85 19]
 [25 17]]
acuracia =  0.6986301369863014
Matriz de confusão
[[92 12]
 [30 12]]
acuracia =  0.7123287671232876
Matriz de confusão
[[90 14]
 [33  9]]
acuracia =  0.678082191780822
Matriz de confusão
[[82 22]
 [27 15]]
acuracia =  0.6643835616438356
Matriz de confusão
[[82 22]
 [29 13]]
acuracia =  0.6506849315068494
Matriz de confusão
[[82 22]
 [27 15]]
acuracia =  0.6643835616438356
Matriz de confusão
[[100   4]
 [ 36   6]]
acuracia =  0.726027397260274
Matriz de confusão
[[92 12]
 [32 10]]
acuracia =  0.6986301369863014
Matriz de confusão
[[97  7]
 [35  7]]
acuracia =  0.7123287671232876
Matriz de confusão
[[95  9]
 [32 10]]
acuracia =  0.7191780821917808
Matriz de confusão
[[95  9]
 [39  3]]
acuracia =  0.6712328767123288
Matriz de confusão
[[92 

## Combinação por Borda Count

In [ ]:
# borda count

for i in range(20):
  #print("-------------- iteracao n ", i, "----------------")
  x_treino,x_temp,y_treino,y_temp=train_test_split(df_dados,dados[10],test_size=0.5,stratify=dados[10], random_state = i)
  x_validacao,x_teste,y_validacao,y_teste=train_test_split(x_temp,y_temp,test_size=0.5, stratify = y_temp, random_state = i)

  # initialize a group of classifiers
  DT = tree.DecisionTreeClassifier(criterion=melhores_parametros_DT['criterion'], max_depth=melhores_parametros_DT['max_depth'],
                                  min_samples_split=melhores_parametros_DT['min_samples_split'], min_samples_leaf=melhores_parametros_DT['min_samples_leaf'])
  DT.fit(x_treino, y_treino)

  KNN = KNeighborsClassifier(n_neighbors=melhor_k, weights=melhor_metrica)
  KNN.fit(x_treino, y_treino)
  #print(KNN.predict(x_teste))

  SVM = svm.SVC(probability=True, C=melhor_c, kernel=melhor_kernel)
  SVM.fit(x_treino, y_treino)

  MLP = MLPClassifier(max_iter=melhores_parametros_MLP['max_iter'], activation=melhores_parametros_MLP['activation'],
                      hidden_layer_sizes=melhores_parametros_MLP['hls'], learning_rate=melhores_parametros_MLP['l_rate'])

  MLP.fit(x_treino, y_treino)

  NB = GaussianNB()
  NB.fit(x_treino, y_treino)

  classifiers = [DT, KNN, SVM, MLP, NB]

  proba_list = []
  for i in classifiers:
    proba_list.append(i.predict_proba(x_teste))

  #elementos na posicao 0 das tuplas são classe 1, posicao 1 sao classe 2
  for i in proba_list:
    for j in i:
      if j[0] > j[1]:
        j[0] = 2
        j[1] = 1
      else:
        j[0] = 1
        j[1] = 2

  resultado_b_count = np.sum(proba_list, axis = 0)

  predicted_classes = []
  for i in resultado_b_count:
    if i[0] > i[1]:
      predicted_classes.append(1)
    else:
      predicted_classes.append(2)

  matrix = confusion_matrix(y_teste, predicted_classes)
  print(matrix)
  accuracy = (matrix[0][0] + matrix[1][1]) / (146)
  print("acuracia = ", accuracy)

[[90 14]
 [28 14]]
acuracia =  0.7123287671232876
[[87 17]
 [26 16]]
acuracia =  0.7054794520547946
[[101   3]
 [ 36   6]]
acuracia =  0.7328767123287672
[[85 19]
 [26 16]]
acuracia =  0.6917808219178082
[[92 12]
 [37  5]]
acuracia =  0.6643835616438356
[[84 20]
 [29 13]]
acuracia =  0.6643835616438356
[[93 11]
 [29 13]]
acuracia =  0.726027397260274
[[91 13]
 [31 11]]
acuracia =  0.6986301369863014
[[79 25]
 [25 17]]
acuracia =  0.6575342465753424
[[92 12]
 [29 13]]
acuracia =  0.7191780821917808
[[97  7]
 [34  8]]
acuracia =  0.7191780821917808
[[93 11]
 [29 13]]
acuracia =  0.726027397260274
[[92 12]
 [31 11]]
acuracia =  0.7054794520547946
[[97  7]
 [34  8]]
acuracia =  0.7191780821917808
[[87 17]
 [30 12]]
acuracia =  0.678082191780822
[[88 16]
 [32 10]]
acuracia =  0.6712328767123288
[[91 13]
 [32 10]]
acuracia =  0.6917808219178082
[[92 12]
 [29 13]]
acuracia =  0.7191780821917808
[[95  9]
 [33  9]]
acuracia =  0.7123287671232876
[[88 16]
 [28 14]]
acuracia =  0.6986301369863014